# Generated by Django 3.1.1 on 2020-10-06 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 10, 6, 13, 32, 31, 332670, tzinfo=utc))),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
