# Generated by Django 3.1.1 on 2020-10-06 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 14, 25, 33, 120959, tzinfo=utc)),
        ),
    ]
